const INSERT_USERS = 'INSERT_USERS';
const ADD_USER = 'ADD_USER';
const UPDATE_USER = 'UPDATE_USER';
const DELETE_USER = 'DELETE_USER';

const INSERT_USER_DATA = 'INSERT_USER_DATA';
const CLEAR_USER_DATA = 'CLEAR_USER_DATA';

const INSERT_ERROR_USER_DATA = 'INSERT_ERROR_USER_DATA';

const INSERT_URL = 'INSERT_URL';

export {
    INSERT_USERS,
    ADD_USER,
    UPDATE_USER,
    DELETE_USER,

    INSERT_USER_DATA,
    CLEAR_USER_DATA,

    INSERT_ERROR_USER_DATA,
    INSERT_URL
};
