const INSERT_USERS = 'INSERT_USERS';
const CLEAR_USERS = 'CLEAR_USERS';
const ADD_USER = 'ADD_USER';
const UPDATE_USER = 'UPDATE_USER';
const DELETE_USER = 'DELETE_USER';

export {
    INSERT_USERS,
    CLEAR_USERS,
    ADD_USER,
    UPDATE_USER,
    DELETE_USER
};
